version: "3"
services:
  clickhouse:
    image: 'yandex/clickhouse-server'
    tmpfs:
      - /var/lib/clickhouse

  nginx:
    image: 'nginx'
    volumes:
      - "./examples/classifier:/usr/share/nginx/html"
      - "./examples/classifier/mime.types:/etc/nginx/mime.types"

  ipcad2ch:
    build: .
    volumes:
      - ".:/go/src/github.com/inkuber/ipcad2ch"
